services:
  - type: web
    name: fin-sight-app
    env: python
    region: oregon  # Optional: choose closest region for better latency
    branch: main  # Ensure your repo’s default branch is 'main'
    
    buildCommand: pip install --no-cache-dir --prefer-binary -r requirements.txt
    
    startCommand: gunicorn app:app  # Ensure your Flask app is named 'app' in app.py

    build:
      pythonVersion: 3.11

    preInstall:
      - apt-get update && apt-get install -y build-essential libpq-dev

    envVars:
      - key: ENV
        value: production
      - key: SECRET_KEY
        value: your-secret-key-here  # Replace with actual secret key
      - key: MONGO_URI
        value: your-mongodb-uri-here  # Add if using MongoDB
