services:
  - type: web
    name: fin-sight-app
    env: python
    region: oregon
    branch: main
    buildCommand: pip install --no-cache-dir --prefer-binary -r requirements.txt && python setup.py
    startCommand: gunicorn app:app
    build:
      pythonVersion: 3.11.9
    envVars:
      - key: ENV
        value: production
