services:
  - type: web
    name: fin-sight-app
    env: python
    region: oregon
    branch: main
    buildCommand: pip install --no-cache-dir --prefer-binary -r requirements.txt
    startCommand: bash start.sh
    build:
      pythonVersion: 3.11.9
    envVars:
      - key: ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.11.9
