services:
  - type: web
    name: fin-sight-app
    env: python
    region: oregon
    branch: main
    buildCommand: pip install --no-cache-dir --prefer-binary -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --timeout 120 --workers 1 --log-level debug --access-logfile - --error-logfile - --capture-output
    build:
      pythonVersion: 3.11.9
    envVars:
      - key: ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.11.9
