services:
  - type: web
    name: fin-sight-app
    env: python
    region: oregon
    branch: main
    buildCommand: pip install --no-cache-dir --prefer-binary -r requirements.txt
    startCommand: gunicorn app:app
    build:
      pythonVersion: 3.11
    preInstall:
      - apt-get update && apt-get install -y build-essential libpq-dev
    envVars:
      - key: ENV
        value: production