services:
  - type: web
    name: fin-sight-app
    env: python
    region: oregon  # or your nearest region
    branch: main
    buildCommand: pip install --prefer-binary -r requirements.txt
    startCommand: gunicorn --chdir . app:app
    build:
      pythonVersion: 3.11  # ✅ Avoid 3.13 — not compatible with some packages
    preInstall:
      - apt-get update && apt-get install -y build-essential libpq-dev
    envVars:
      - key: ENV
        value: production
